version: "3.8"

services:
  ### CONTAINERS ###
  payment-service:
    build:
      context: payment-service/api
      dockerfile: ./Dockerfile
    container_name: "payment-service"
    volumes:
      - ./payment-service/api/src:/var/www/html
    ## Expose the API for debugging
    # ports:
      # - "9001:9001"

  payment-service-nginx:
    build:
      context: payment-service/nginx
      dockerfile: ./Dockerfile
    container_name: "payment-service-nginx"
    ports:
      - "8070:80"

  payment-db-adminer:
    image: adminer:latest
    container_name: "payment-db-adminer"
    environment:
      ADMINER_DEFAULT_SERVER: payment-sql
    ports:
      - 8083:8080
    depends_on:
      - payment-sql

  payment-sql:
    image: mysql:8.0.33-debian
    container_name: "payment-sql"
    ports:
      - 8080:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: payment-service
      MYSQL_PASSWORD: payment-pass
    volumes:
      - payment-app-data-volume:/var/lib/mysql
      - ./payment-service/database:/docker-entrypoint-initdb.d

volumes:
  payment-app-data-volume:
