/* Universal and commercial banks */
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Al-Amanah Islamic Investment Bank of the Philippines", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Asia United Bank Corporation", "AUB", 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Australia and New Zealand Banking Group Ltd.", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Bangkok Bank Public Co. Ltd.", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Bank of America, N.A", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Bank of China (Hongkong) Limited-Manila Branch", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Bank of Commerce", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Bank of the Philippine Islands", "BPI", 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("BDO Unibank, Inc.", "BDO", 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Cathay United Bank Co., Ltd. - Manila Branch", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("China Banking Corporation", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("CIMB Bank Philippines, Inc.", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Citibank, N.A.", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("CTBC Bank (Philippines) Corporation", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Deutsche Bank AG", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Development Bank of the Philippines", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("East West Banking Corporation", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Industrial and Commercial Bank of China, Ltd. - Manila Branch", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Industrial Bank of Korea Manila Branch", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("JP Morgan Chase Bank, N.A.", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("KEB Hana Bank - Manila Branch", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Land Bank of the Philippines", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Maybank Philippines, Inc.", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Mega International Commercial Bank Co., Ltd.", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Metropolitan Bank and Trust Company", "Metrobank", 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Mizuho Bank, Ltd. - Manila Branch", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("MUFG Bank, Ltd.", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Philippine Bank of Communications", "PBOC", 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Philippine National Bank", "PNB", 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Philippine Trust Company", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Philippine Veterans Bank", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Rizal Commercial Banking Corporation", "RCBC", 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Robinsons Bank Corporation", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Security Bank Corporation", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Shinhan Bank - Manila Branch", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Standard Chartered Bank", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Sumitomo Mitsui Banking Corporation - Manila Branch", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("The Hongkong & Shanghai Banking Corporation", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Union Bank of the Philippines", NULL, 1);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("United Overseas Bank Limited, Manila Branch", NULL, 1);

/* Thrift Banks */
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("AllBank (A Thrift Bank), Inc.", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Bangko Kabayan, Inc. (A Private Development Bank)", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Bank of Makati (A Savings Bank), Inc.", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("BPI Direct BanKO, Inc., A Savings Bank", "BPI Direct BanKO", 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Card SME Bank Inc., A Thrift Bank", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("China Bank Savings, Inc.", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Dumaguete City Development Bank, Inc.", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Equicom Savings Bank, Inc.", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("First Consolidated Bank, Inc. (A Private Development Bank)", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("HSBC Savings Bank (Phils), Inc.", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("ISLA Bank (A Thrift Bank), Inc.", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Legazpi Savings Bank, Inc.", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Luzon Development Bank", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Malayan Savings Bank, Inc.", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Pacific Ace Savings Bank, Inc.", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Philippine Business Bank, Inc., A Savings Bank", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Philippine Savings Bank", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Producers Savings Bank Corporation", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Queen City Development Bank, Inc. ", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Sterling Bank of Asia, Inc. (A Savings Bank)", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Sun Savings Bank, Inc.", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("UCPB Savings Bank", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Wealth Development Bank Corporation", NULL, 2);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Yuanta Savings Bank Philippines, Inc.", NULL, 2);

/* Rural Banks */
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Bangko Mabuhay (A Rural Bank), Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Bangko Nuestra Senora del Pilar, Inc. (A Rural Bank)", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("BDO Network Bank, Inc. (A Rural Bank)", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Biñan Rural Bank, Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("BOF, Inc. (A Rural Bank)", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Camalig Bank, Inc. (A Rural Bank)", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Cantilan Bank, Inc. (A Rural Bank)", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Card Bank, Inc. (A MicrofinanceOriented Rural Bank)", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Cebuana Lhuillier Rural Bank, Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Cooperative Bank of Quezon Province", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Country Builders Bank, Inc. (A Rural Bank)", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Dungganon Bank (A Microfinance Rural Bank), Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Dungganon Bank (A MicrofinanceRural Bank), Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("East West Rural Bank, Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Entrepreneur Rural Bank, Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Guagua Rural Bank, Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Innovative Rural Bank, Inc. (A Rural Bank)", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Laguna Prestige Banking Corporation, (A Rural Bank)", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Malarayat Rural Bank, Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Mindanao Consolidated Cooperative Bank", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Money Mall Rural Bank, Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("MVSM Bank (Rural Bank Since 1953), Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Netbank (A Rural Bank), Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("New Rural Bank of San Leonardo (Nueva Ecija), Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Partner Rural Bank (Cotabato), Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Quezon Capital Rural Bank, Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Rang-Ay Bank, Inc. (A Rural Bank)", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("RBT Bank, Inc., A Rural Bank", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Rural Bank of Bacolod City, Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Rural Bank of Bauang, Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Rural Bank of Digos, Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Rural Bank of Guinobatan, Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Rural Bank of La Paz, Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Rural Bank of Lebak (Sultan Kudarat), Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Rural Bank of Montalban, Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Rural Bank of Porac (Pampanga), Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Rural Bank of Rosario (La Union), Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Rural Bank of Sagay, Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Rural Bank of Sta. Ignacia, Inc.", NULL, 3);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("SeaBank Philippines Inc. (A Rural Bank)", NULL, 3);

/* Digital Banks */
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("GoTyme Bank Corporation", NULL, 4);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Maya Bank, Inc.", NULL, 4);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Tonik Digital Bank, Inc.", NULL, 4);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Union Digital Bank", NULL, 4);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("UNObank, Inc.", NULL, 4);

/* Electronic Money Issuers / Others */
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Alipay Philippines, Inc.", NULL, 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("CIS Bayad Center, Inc.", NULL, 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("DCPAY Philippines, Inc.", "Coins.ph", 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("G-Xchange, Inc. (GXI)", "GCash", 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Gpay Network PH, Inc.", NULL, 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("I-Remit, Inc.", NULL, 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Infoserve, Inc.", NULL, 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Lulu Financial Services (Phils.), Inc.", NULL, 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("OmniPay, Inc.", NULL, 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Paymongo Payments, Inc.", NULL, 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Philippine Digital Asset Exchange, Inc.", NULL, 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("PPS-PEPP Financial Services Corp.", NULL, 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("ShopeePay Philippines, Inc.", NULL, 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("SpeedyPay, Inc.", NULL, 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("StarPay Corporation", NULL, 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("TayoCash, Inc.", NULL, 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Traxion Pay, Inc.", NULL, 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("USSC Money Services, Inc.", NULL, 5);
INSERT INTO `financial_institutions` (name, short_name, type) VALUES ("Zybi Tech, Inc.", NULL, 5);
