name: payment-app-linter-and-formatter
run-name: ${{ github.actor }} is linting and formatting Payment App
on:
  push:
    branches:
      - main
      - develop
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
          cache-dependency-path: /home/runner/work/send-money-app/send-money-app/payment-app/web/package-lock.json
      - name: Install Node
        working-directory: ./payment-app/web
        run: npm install
      - name: Run linter
        working-directory: ./payment-app/web
        run: npm run lint
      - name: Format the codes and compare
        working-directory: ./payment-app/web
        run: |
          npm run format
          if ! git diff --exit-code; then
            echo "Code formatting issues detected. Please run 'npm run format' and commit the changes."
            exit 1
          fi
